---
title: "DESeq2"
author: "Himanshu Chintalapudi"
date: "October 10, 2017"
output:
  html_document: default
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
source("http://www.bioconductor.org/biocLite.R")

```


```{r}
library("pasilla")
pasCts <- system.file("extdata","pasilla_gene_counts.tsv",package="pasilla", mustWork=TRUE)

pasAnno <- system.file("extdata","pasilla_sample_annotation.csv",package="pasilla", mustWork=TRUE)

cts <- as.matrix(read.csv(pasCts,sep="\t",row.names="gene_id"))

coldata <- read.csv(pasAnno, row.names=1)
coldata <- coldata[,c("condition","type")]

head(cts)

head(coldata)

rownames(coldata) <- sub("fb","",rownames(coldata))
all(rownames(coldata) %in% colnames(cts))

cts <- cts[, rownames(coldata)]
all(rownames(coldata) == colnames(cts))

install.packages("DESeq2")
install.packages("data.table")
library(data.table)
library("DESeq2")
dds <- DESeqDataSetFromMatrix(countData = cts,colData = coldata,design = ~ condition)
dds

featureData <- data.frame(gene=rownames(cts))
mcols(dds) <- DataFrame(mcols(dds), featureData)
mcols(dds)

```

#Differential expression analysis


```{r}

dds <- DESeq(dds)
res <- results(dds)
#res

resultsNames(dds)

library("BiocParallel")
register(SnowParam(4))

resOrdered <- res[order(res$padj),]
summary(res)

sum(res$padj < 0.1, na.rm = TRUE)

res05 <- results(dds, alpha=0.05)
summary(res05)

sum(res05$padj < 0.05, na.rm=TRUE)

library("IHW")
resIHW <- results(dds, filterFun=ihw)
summary(resIHW)

sum(resIHW$padj < 0.1, na.rm=TRUE)

metadata(resIHW)$ihwResult


```

#Exploring and exporting results

```{r}
plotMA(res, ylim=c(-2,2))
#res

#idx <- identify(res$baseMean, res$log2FoldChange)
#rownames(res)[idx]
#log <- res$log2FoldChange
#mean <- res$baseMean
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

h = ggplot(data = a, aes(res$log2FoldChange, -log10(res$padj), colour= threshold))+ geom_point(alpha = 0.4, size=1.5)+ xlim(c(-4,4)) + ylim(c(0,75))
h

#plot(mean,log)
library(ggplot2)
#qplot(mean,log, ylim = c(-2,2), xlim = c(0,10000)) 
a <- as.data.frame(res)
a$threshold = as.factor(abs(a$log2FoldChange) >2 & a$padj<0.9)
g = ggplot(data = a, aes(res$log2FoldChange, -log10(res$padj), colour=threshold))+ geom_point(alpha = 0.4, size=1.5)+ xlim(c(-4,4)) + ylim(c(0,75))
g
#idx <- identify(res$log2FoldChange, res$padj)
#rownames(res)[idx]
h = ggplot(data = a) + geom_point(mapping = aes(x = res$baseMean, y = res$log2FoldChange))
h
```

# Plot Counts

```{r}
plotCounts(dds, gene=which.min(res$padj), intgroup="condition")

d <- plotCounts(dds, gene=which.min(res$padj), intgroup="condition", returnData=TRUE)

ggplot(d, aes(x=condition, y=count)) + geom_point(position=position_jitter(w=0.1,h=0)) + scale_y_log10(breaks=c(25,100,400))


```

#Multi-factor designs


```{r}
#colData(dds)

ddsMF <- dds
design(ddsMF) <- formula(~ type + condition)
resMF <- results(ddsMF)


#resMFType <- results(ddsMF,contrast = c("type","single-read","paired-end"))
#head(resMFType)
```

#Data transformations and visualization

```{r}

rld <- rlog(dds, blind=FALSE)
vsd <- varianceStabilizingTransformation(dds, blind=FALSE)
vsd.fast <- vst(dds, blind=FALSE)
head(assay(rld), 3)

```


```{r}

ntd <- normTransform(dds)
library("vsn")
notAllZero <- (rowSums(counts(dds))>0)
meanSdPlot(assay(ntd)[notAllZero,])

meanSdPlot(assay(rld[notAllZero,]))

meanSdPlot(assay(vsd[notAllZero,]))


```

# Heat Map

```{r}
library("pheatmap")
select <- order(rowMeans(counts(dds,normalized=TRUE)),decreasing=TRUE)[1:20]

df <- as.data.frame(colData(dds)[,c("condition","type")])
pheatmap(assay(ntd)[select,], cluster_rows=FALSE, show_rownames=FALSE,cluster_cols=FALSE, annotation_col=df)

```

# Heatmap of the sample-to-sample distances


```{r}

sampleDists <- dist(t(assay(rld)))

library("RColorBrewer")

sampleDistMatrix <- as.matrix(sampleDists)

rownames(sampleDistMatrix) <- paste(rld$condition,rld$type, sep="-")

colnames(sampleDistMatrix) <- NULL

colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)

pheatmap(sampleDistMatrix,clustering_distance_rows=sampleDists,clustering_distance_cols=sampleDists,col=colors)

```



```{r}

heatmap(assay(vsd)[select,], cluster_rows = TRUE)


```

# Principal component plot of the samples

```{r}

plotPCA(rld, intgroup=c("condition", "type"))

```

# dendrogram

```{r}
#pd <- dist(scale(assay(rld)))

#hc <- hclust(pd)
#plot(hc)
```
